-- Minimal seed: Solana ecosystem sources (Phase 1 + expansion pass 1)

INSERT INTO sources (slug, name, source_type, base_url, feed_url, reliability, is_enabled, requires_api_key, status, metadata_json)
VALUES
  (
    'solana-blog',
    'Solana Foundation Blog',
    'rss',
    'https://solana.com',
    'https://solana.com/news/rss.xml',
    0.90,
    true,
    false,
    'active',
    '{"purpose": "official ecosystem announcements", "fallback": "manual cache"}'::jsonb
  ),
  (
    'helius-blog',
    'Helius Blog',
    'rss',
    'https://www.helius.dev/blog',
    'https://www.helius.dev/blog/rss.xml',
    0.88,
    true,
    false,
    'active',
    '{"purpose": "infra / dev / ecosystem", "max_items_per_run": 25}'::jsonb
  ),
  (
    'raydium-medium',
    'Raydium — Medium',
    'rss',
    'https://medium.com/@raydium',
    'https://medium.com/feed/@raydium',
    0.84,
    true,
    false,
    'active',
    '{"purpose": "DeFi / project official updates"}'::jsonb
  ),
  (
    'the-block-news',
    'The Block — News',
    'rss',
    'https://www.theblock.co',
    'https://www.theblock.co/rss.xml',
    0.85,
    true,
    false,
    'active',
    '{"purpose": "general crypto news (Solana-filtered at ingest)", "requires_solana_filter": true, "max_items_per_run": 15}'::jsonb
  ),
  (
    'solana-status',
    'Solana Status',
    'rss',
    'https://status.solana.com',
    'https://status.solana.com/history.rss',
    0.92,
    true,
    false,
    'active',
    '{"purpose": "infra / security / incidents"}'::jsonb
  ),
  (
    'marinade-blog',
    'Marinade Blog',
    'rss',
    'https://marinade.finance/blog',
    'https://marinade.finance/blog/rss.xml',
    0.86,
    true,
    false,
    'active',
    '{"purpose": "DeFi / LST / staking", "max_items_per_run": 15, "coverage": "defi_lst"}'::jsonb
  ),
  (
    'orca-medium',
    'Orca — Medium',
    'rss',
    'https://orca-so.medium.com',
    'https://orca-so.medium.com/feed',
    0.85,
    true,
    false,
    'active',
    '{"purpose": "DeFi / DEX official publication", "max_items_per_run": 10, "coverage": "defi_dex"}'::jsonb
  ),
  (
    'pyth-status',
    'Pyth Network Status',
    'rss',
    'https://status.pyth.network',
    'https://status.pyth.network/history.rss',
    0.90,
    true,
    false,
    'active',
    '{"purpose": "infra / oracle / incidents", "max_items_per_run": 10, "coverage": "infra_oracle"}'::jsonb
  ),
  (
    'sanctum-medium',
    'Sanctum — Medium',
    'rss',
    'https://medium.com/@sanctumso',
    'https://medium.com/feed/@sanctumso',
    0.82,
    true,
    false,
    'active',
    '{"purpose": "DeFi / LST / restaking", "max_items_per_run": 5, "coverage": "defi_lst"}'::jsonb
  ),
  (
    'the-block-solana',
    'The Block — Solana',
    'rss',
    'https://www.theblock.co',
    NULL,
    0.85,
    false,
    false,
    'paused',
    '{"purpose": "legacy placeholder — use the-block-news", "status": "superseded by the-block-news"}'::jsonb
  ),
  (
    'dexscreener-solana',
    'DexScreener — Solana Pairs',
    'dexscreener',
    'https://dexscreener.com',
    'https://api.dexscreener.com/latest/dex/tokens/solana',
    0.75,
    true,
    false,
    'active',
    '{"purpose": "new pair and volume signals", "rate_limit": "public, unauthenticated"}'::jsonb
  ),
  (
    'defillama-solana',
    'DefiLlama — Solana TVL',
    'defillama',
    'https://defillama.com',
    'https://api.llama.fi/v2/chains',
    0.88,
    true,
    false,
    'active',
    '{"purpose": "protocol TVL and chain metrics", "fallback": "stale snapshot"}'::jsonb
  ),
  (
    'defillama-fees-solana',
    'DefiLlama — Solana Fees',
    'defillama',
    'https://defillama.com',
    'https://api.llama.fi/overview/fees/solana?excludeTotalDataChart=true',
    0.88,
    true,
    false,
    'active',
    '{"purpose": "protocol revenue / fees on Solana"}'::jsonb
  ),
  (
    'manual-curator',
    'Manual Curator Notes',
    'manual',
    NULL,
    NULL,
    0.70,
    true,
    false,
    'active',
    '{"purpose": "human-in-the-loop watchlist items", "editor": "internal"}'::jsonb
  ),
  (
    'solanafloor-sitemap',
    'SolanaFloor — News (sitemap)',
    'sitemap',
    'https://solanafloor.com',
    'https://solanafloor.com/news/sitemap.xml',
    0.75,
    true,
    false,
    'active',
    '{"purpose": "headline-only discovery via public news sitemap", "max_items_per_run": 15, "max_age_hours": 168, "discovery": "sitemap", "no_article_fetch": true}'::jsonb
  ),
  (
    'drift-medium',
    'Drift — Medium',
    'rss',
    'https://medium.com/@driftprotocol',
    'https://medium.com/feed/@driftprotocol',
    0.84,
    true,
    false,
    'active',
    '{"purpose": "DeFi / perps official updates", "max_items_per_run": 10, "coverage": "defi_perps"}'::jsonb
  ),
  (
    'metaplex-medium',
    'Metaplex — Medium',
    'rss',
    'https://medium.com/@metaplex',
    'https://medium.com/feed/@metaplex',
    0.84,
    true,
    false,
    'active',
    '{"purpose": "NFT / protocol official updates", "max_items_per_run": 10, "coverage": "nft_protocol"}'::jsonb
  ),
  (
    'magiceden-status',
    'Magic Eden — Status',
    'rss',
    'https://status.magiceden.io',
    'https://status.magiceden.io/history.rss',
    0.90,
    true,
    false,
    'active',
    '{"purpose": "NFT marketplace incidents / maintenance", "max_items_per_run": 10, "coverage": "nft_status"}'::jsonb
  ),
  (
    'dlnews-rss',
    'DL News — RSS',
    'rss',
    'https://www.dlnews.com',
    'https://www.dlnews.com/arc/outboundfeeds/rss/',
    0.78,
    true,
    false,
    'active',
    '{"purpose": "DeFi / ecosystem news (Solana-filtered at ingest)", "requires_solana_filter": true, "max_items_per_run": 10, "coverage": "ecosystem_editorial"}'::jsonb
  ),
  (
    'decrypt-rss',
    'Decrypt — RSS',
    'rss',
    'https://decrypt.co',
    'https://decrypt.co/feed',
    0.76,
    true,
    false,
    'active',
    '{"purpose": "ecosystem / NFT / gaming news (Solana-filtered at ingest)", "requires_solana_filter": true, "max_items_per_run": 10, "coverage": "ecosystem_editorial"}'::jsonb
  ),
  (
    'coindesk-rss',
    'CoinDesk — RSS',
    'rss',
    'https://www.coindesk.com',
    'https://www.coindesk.com/arc/outboundfeeds/rss/',
    0.78,
    true,
    false,
    'active',
    '{"purpose": "Broad crypto editorial (Solana-filtered at ingest) — Wave 3 trial", "requires_solana_filter": true, "max_items_per_run": 5, "coverage": "ecosystem_editorial", "broad_rss_trial": true, "official_source": false}'::jsonb
  ),
  (
    'agave-releases',
    'Agave — GitHub Releases',
    'rss',
    'https://github.com/anza-xyz/agave',
    'https://github.com/anza-xyz/agave/releases.atom',
    0.88,
    true,
    false,
    'active',
    '{"purpose": "validator client releases (Anza/Agave)", "feed_format": "atom", "max_items_per_run": 5, "coverage": "infra_builder", "builder_source": true}'::jsonb
  ),
  (
    'firedancer-releases',
    'Firedancer — GitHub Releases',
    'rss',
    'https://github.com/firedancer-io/firedancer',
    'https://github.com/firedancer-io/firedancer/releases.atom',
    0.86,
    true,
    false,
    'active',
    '{"purpose": "Firedancer / Frankendancer client releases", "feed_format": "atom", "max_items_per_run": 5, "coverage": "infra_builder", "builder_source": true}'::jsonb
  ),
  (
    'jito-solana-releases',
    'Jito Solana — GitHub Releases',
    'rss',
    'https://github.com/jito-foundation/jito-solana',
    'https://github.com/jito-foundation/jito-solana/releases.atom',
    0.86,
    true,
    false,
    'active',
    '{"purpose": "Jito validator / MEV client releases", "feed_format": "atom", "max_items_per_run": 5, "coverage": "infra_builder", "builder_source": true}'::jsonb
  )
ON CONFLICT (slug) DO NOTHING;
